-- Privacy-minimal product analytics for the public beta. Raw events contain
-- only fixed operational dimensions; user-authored text, image URLs, request
-- bodies, IP addresses, and arbitrary JSON properties are intentionally absent.

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  event_key text not null,
  event_name text not null,
  uid text references public.app_users(uid) on delete set null,
  module text,
  ingestion_source text not null,
  size_bytes bigint,
  source_scene integer,
  source_campaign text,
  source_referrer_app_id text,
  release_channel text,
  occurred_at timestamptz not null default now(),
  recorded_at timestamptz not null default now(),
  constraint product_events_event_key_unique unique (event_key),
  constraint product_events_event_key_length
    check (char_length(event_key) between 8 and 240),
  constraint product_events_name_check
    check (event_name in (
      'registration_completed',
      'login_succeeded',
      'module_opened',
      'content_created',
      'image_uploaded'
    )),
  constraint product_events_module_check
    check (module is null or module in (
      'home',
      'menu',
      'media',
      'activities',
      'chat_topics',
      'text_card',
      'exercise',
      'luggage',
      'wardrobe',
      'key_moments',
      'footprint',
      'profile'
    )),
  constraint product_events_module_required_check
    check (
      (event_name in ('registration_completed', 'login_succeeded') and module is null)
      or
      (event_name in ('module_opened', 'content_created', 'image_uploaded') and module is not null)
    ),
  constraint product_events_ingestion_source_check
    check (ingestion_source in ('server', 'client')),
  constraint product_events_bytes_check
    check (
      (event_name = 'image_uploaded' and size_bytes is not null and size_bytes > 0)
      or
      (event_name <> 'image_uploaded' and size_bytes is null)
    ),
  constraint product_events_scene_check
    check (source_scene is null or source_scene between 0 and 99999),
  constraint product_events_campaign_length
    check (source_campaign is null or char_length(source_campaign) between 1 and 64),
  constraint product_events_referrer_length
    check (
      source_referrer_app_id is null
      or char_length(source_referrer_app_id) between 3 and 64
    ),
  constraint product_events_release_channel_check
    check (release_channel is null or release_channel in ('develop', 'trial', 'release')),
  constraint product_events_time_check
    check (occurred_at <= recorded_at + interval '5 minutes')
);

create index if not exists product_events_occurred_idx
  on public.product_events (occurred_at desc);
create index if not exists product_events_name_occurred_idx
  on public.product_events (event_name, occurred_at desc);
create index if not exists product_events_uid_occurred_idx
  on public.product_events (uid, occurred_at desc)
  where uid is not null;
create index if not exists product_events_module_occurred_idx
  on public.product_events (module, occurred_at desc)
  where module is not null;

alter table public.product_events enable row level security;
revoke all on table public.product_events from public, anon, authenticated;
grant select, insert, delete on table public.product_events to service_role;
revoke all on sequence public.product_events_id_seq from public, anon, authenticated;
grant usage, select on sequence public.product_events_id_seq to service_role;

-- Preserve the two existing accounts as historical registrations without
-- fabricating source attribution or historical usage that was never observed.
insert into public.product_events (
  event_key,
  event_name,
  uid,
  ingestion_source,
  occurred_at,
  recorded_at
)
select
  'registration:' || app_user.uid,
  'registration_completed',
  app_user.uid,
  'server',
  app_user.created_at,
  now()
from public.app_users as app_user
on conflict (event_key) do nothing;

create or replace view public.product_daily_overview
with (security_invoker = true)
as
with product_days as (
  select
    (event.occurred_at at time zone 'Asia/Shanghai')::date as metric_date,
    count(*) filter (where event.event_name = 'registration_completed')::bigint
      as registrations,
    count(*) filter (where event.event_name = 'login_succeeded')::bigint
      as logins,
    count(distinct event.uid) filter (where event.uid is not null)::bigint
      as active_users,
    count(*) filter (where event.event_name = 'module_opened')::bigint
      as module_opens,
    count(*) filter (where event.event_name = 'content_created')::bigint
      as content_creations,
    count(*) filter (where event.event_name = 'image_uploaded')::bigint
      as image_uploads,
    coalesce(sum(event.size_bytes) filter (where event.event_name = 'image_uploaded'), 0)::bigint
      as uploaded_bytes
  from public.product_events as event
  group by (event.occurred_at at time zone 'Asia/Shanghai')::date
), operational_days as (
  select
    (event.bucket_started_at at time zone 'Asia/Shanghai')::date as metric_date,
    coalesce(sum(event.occurrence_count) filter (
      where event.severity in ('error', 'critical')
    ), 0)::bigint as error_occurrences,
    coalesce(sum(event.occurrence_count) filter (
      where event.severity = 'warning'
    ), 0)::bigint as warning_occurrences
  from public.operational_events as event
  group by (event.bucket_started_at at time zone 'Asia/Shanghai')::date
), metric_dates as (
  select metric_date from product_days
  union
  select metric_date from operational_days
)
select
  metric_dates.metric_date,
  coalesce(product_days.registrations, 0)::bigint as registrations,
  coalesce(product_days.logins, 0)::bigint as logins,
  coalesce(product_days.active_users, 0)::bigint as active_users,
  coalesce(product_days.module_opens, 0)::bigint as module_opens,
  coalesce(product_days.content_creations, 0)::bigint as content_creations,
  coalesce(product_days.image_uploads, 0)::bigint as image_uploads,
  coalesce(product_days.uploaded_bytes, 0)::bigint as uploaded_bytes,
  coalesce(operational_days.error_occurrences, 0)::bigint as error_occurrences,
  coalesce(operational_days.warning_occurrences, 0)::bigint as warning_occurrences
from metric_dates
left join product_days using (metric_date)
left join operational_days using (metric_date);

create or replace view public.product_module_daily
with (security_invoker = true)
as
select
  (event.occurred_at at time zone 'Asia/Shanghai')::date as metric_date,
  event.module,
  count(distinct event.uid) filter (where event.uid is not null)::bigint as unique_users,
  count(*) filter (where event.event_name = 'module_opened')::bigint as module_opens,
  count(*) filter (where event.event_name = 'content_created')::bigint as content_creations,
  count(*) filter (where event.event_name = 'image_uploaded')::bigint as image_uploads,
  coalesce(sum(event.size_bytes) filter (where event.event_name = 'image_uploaded'), 0)::bigint
    as uploaded_bytes
from public.product_events as event
where event.module is not null
group by
  (event.occurred_at at time zone 'Asia/Shanghai')::date,
  event.module;

create or replace view public.product_source_daily
with (security_invoker = true)
as
select
  (event.occurred_at at time zone 'Asia/Shanghai')::date as metric_date,
  event.source_scene,
  event.source_campaign,
  event.source_referrer_app_id,
  event.release_channel,
  count(*)::bigint as registrations
from public.product_events as event
where event.event_name = 'registration_completed'
group by
  (event.occurred_at at time zone 'Asia/Shanghai')::date,
  event.source_scene,
  event.source_campaign,
  event.source_referrer_app_id,
  event.release_channel;

create or replace view public.product_current_summary
with (security_invoker = true)
as
select
  (select count(*)::bigint from public.app_users) as total_users,
  (
    select count(*)::bigint
    from public.app_users
    where last_login_at >= now() - interval '30 days'
  ) as users_logged_in_30d,
  (select count(*)::bigint from public.image_assets) as image_count,
  (
    select coalesce(sum(size_bytes), 0)::bigint
    from public.image_assets
  ) as current_image_bytes,
  (
    select count(*)::bigint
    from public.operational_events
    where resolved_at is null and severity in ('error', 'critical')
  ) as open_error_groups;

do $$
declare
  view_name text;
begin
  foreach view_name in array array[
    'product_daily_overview',
    'product_module_daily',
    'product_source_daily',
    'product_current_summary'
  ]
  loop
    execute format(
      'revoke all on table public.%I from public, anon, authenticated',
      view_name
    );
    execute format(
      'grant select on table public.%I to service_role',
      view_name
    );
  end loop;
end
$$;
