-- Public-beta safety controls, image quotas, audit history, and structured
-- operational events. All tables remain service-only; the mini program uses
-- authenticated Node routes instead of direct Data API access.

create table if not exists public.runtime_controls (
  key text primary key,
  enabled boolean not null,
  message text not null,
  updated_by_uid text references public.app_users(uid) on delete set null,
  updated_at timestamptz not null default now(),
  constraint runtime_controls_key_check
    check (key in ('registration_enabled', 'write_enabled')),
  constraint runtime_controls_message_length
    check (char_length(message) between 1 and 200)
);

insert into public.runtime_controls (key, enabled, message)
values
  ('registration_enabled', true, '当前暂时停止新用户注册，请稍后再试。'),
  ('write_enabled', true, '系统正在维护，当前暂时只能查看已有内容。')
on conflict (key) do nothing;

create table if not exists public.runtime_control_audits (
  id bigint generated by default as identity primary key,
  control_key text not null,
  previous_enabled boolean not null,
  next_enabled boolean not null,
  reason text not null,
  operator_uid text references public.app_users(uid) on delete set null,
  created_at timestamptz not null default now(),
  constraint runtime_control_audits_key_check
    check (control_key in ('registration_enabled', 'write_enabled')),
  constraint runtime_control_audits_reason_length
    check (char_length(reason) between 2 and 200)
);

create index if not exists runtime_control_audits_created_idx
  on public.runtime_control_audits (created_at desc);

create table if not exists public.image_storage_limits (
  uid text primary key references public.app_users(uid) on delete cascade,
  quota_bytes bigint not null default 104857600 check (quota_bytes > 0),
  warning_bytes bigint not null default 83886080 check (warning_bytes >= 0),
  updated_at timestamptz not null default now(),
  constraint image_storage_limits_warning_check
    check (warning_bytes < quota_bytes)
);

insert into public.image_storage_limits (uid)
select app_user.uid
from public.app_users as app_user
on conflict (uid) do nothing;

create or replace function public.ensure_image_storage_limit()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  insert into public.image_storage_limits (uid)
  values (new.uid)
  on conflict (uid) do nothing;
  return new;
end;
$$;

drop trigger if exists app_users_ensure_image_storage_limit
  on public.app_users;
create trigger app_users_ensure_image_storage_limit
after insert on public.app_users
for each row execute function public.ensure_image_storage_limit();

drop function if exists public.get_user_image_storage_usage(text);
create function public.get_user_image_storage_usage(p_uid text)
returns table (
  module text,
  image_count bigint,
  used_bytes bigint,
  quota_bytes bigint,
  warning_bytes bigint
)
language sql
stable
security invoker
set search_path = public
as $$
  with modules(module, sort_order) as (
    values
      ('menu', 1),
      ('activities', 2),
      ('media', 3),
      ('wardrobe', 4),
      ('key_moments', 5),
      ('avatars', 6)
  ), account_limit as (
    select
      coalesce(storage_limit.quota_bytes, 104857600::bigint) as quota_bytes,
      coalesce(storage_limit.warning_bytes, 83886080::bigint) as warning_bytes
    from (select 1) as singleton
    left join public.image_storage_limits as storage_limit
      on storage_limit.uid = p_uid
  )
  select
    modules.module,
    count(image_asset.object_key)::bigint,
    coalesce(sum(image_asset.size_bytes), 0)::bigint,
    account_limit.quota_bytes,
    account_limit.warning_bytes
  from modules
  cross join account_limit
  left join public.image_assets as image_asset
    on image_asset.module = modules.module
   and image_asset.uid = p_uid
  group by
    modules.module,
    modules.sort_order,
    account_limit.quota_bytes,
    account_limit.warning_bytes
  order by modules.sort_order;
$$;

create or replace function public.update_runtime_control(
  p_key text,
  p_enabled boolean,
  p_reason text,
  p_uid text
)
returns table (
  key text,
  enabled boolean,
  message text,
  updated_by_uid text,
  updated_at timestamptz
)
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_control public.runtime_controls%rowtype;
  normalized_reason text := btrim(coalesce(p_reason, ''));
begin
  if p_key not in ('registration_enabled', 'write_enabled') then
    raise exception using errcode = '22023', message = 'RUNTIME_CONTROL_INVALID';
  end if;
  if char_length(normalized_reason) < 2 or char_length(normalized_reason) > 200 then
    raise exception using errcode = '22023', message = 'RUNTIME_CONTROL_REASON_INVALID';
  end if;
  if not exists (select 1 from public.app_users where uid = p_uid) then
    raise exception using errcode = '22023', message = 'RUNTIME_CONTROL_OPERATOR_INVALID';
  end if;

  select * into current_control
  from public.runtime_controls as control
  where control.key = p_key
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'RUNTIME_CONTROL_NOT_FOUND';
  end if;
  if current_control.enabled = p_enabled then
    raise exception using errcode = '22023', message = 'RUNTIME_CONTROL_UNCHANGED';
  end if;

  update public.runtime_controls as control
  set
    enabled = p_enabled,
    updated_by_uid = p_uid,
    updated_at = now()
  where control.key = p_key;

  insert into public.runtime_control_audits (
    control_key,
    previous_enabled,
    next_enabled,
    reason,
    operator_uid
  ) values (
    p_key,
    current_control.enabled,
    p_enabled,
    normalized_reason,
    p_uid
  );

  return query
  select
    control.key,
    control.enabled,
    control.message,
    control.updated_by_uid,
    control.updated_at
  from public.runtime_controls as control
  where control.key = p_key;
end;
$$;

create table if not exists public.operational_events (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null,
  bucket_started_at timestamptz not null,
  request_id text not null,
  severity text not null check (severity in ('warning', 'error', 'critical')),
  category text not null,
  error_code text not null,
  method text not null,
  route text not null,
  status_code integer not null check (status_code between 400 and 599),
  uid text references public.app_users(uid) on delete set null,
  message text not null,
  details jsonb not null default '{}'::jsonb,
  occurrence_count bigint not null default 1 check (occurrence_count > 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolution_note text,
  constraint operational_events_fingerprint_length
    check (char_length(fingerprint) between 16 and 128),
  constraint operational_events_message_length
    check (char_length(message) between 1 and 1000),
  constraint operational_events_unique_bucket
    unique (fingerprint, bucket_started_at)
);

create index if not exists operational_events_last_seen_idx
  on public.operational_events (last_seen_at desc);
create index if not exists operational_events_open_severity_idx
  on public.operational_events (severity, last_seen_at desc)
  where resolved_at is null;
create index if not exists operational_events_request_idx
  on public.operational_events (request_id);
create index if not exists operational_events_uid_idx
  on public.operational_events (uid, last_seen_at desc)
  where uid is not null;

create or replace function public.record_operational_event(
  p_fingerprint text,
  p_bucket_started_at timestamptz,
  p_request_id text,
  p_severity text,
  p_category text,
  p_error_code text,
  p_method text,
  p_route text,
  p_status_code integer,
  p_uid text,
  p_message text,
  p_details jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  event_id uuid;
begin
  insert into public.operational_events (
    fingerprint,
    bucket_started_at,
    request_id,
    severity,
    category,
    error_code,
    method,
    route,
    status_code,
    uid,
    message,
    details
  ) values (
    left(p_fingerprint, 128),
    date_trunc('hour', p_bucket_started_at),
    left(p_request_id, 120),
    p_severity,
    left(p_category, 80),
    left(p_error_code, 120),
    left(p_method, 12),
    left(p_route, 500),
    p_status_code,
    p_uid,
    left(p_message, 1000),
    coalesce(p_details, '{}'::jsonb)
  )
  on conflict (fingerprint, bucket_started_at)
  do update set
    request_id = excluded.request_id,
    status_code = excluded.status_code,
    uid = coalesce(excluded.uid, operational_events.uid),
    message = excluded.message,
    details = excluded.details,
    occurrence_count = operational_events.occurrence_count + 1,
    last_seen_at = now(),
    resolved_at = null,
    resolution_note = null
  returning id into event_id;

  return event_id;
end;
$$;

create or replace function public.cleanup_operational_events(p_cutoff timestamptz)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  delete from public.operational_events
  where last_seen_at < p_cutoff;
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

alter table public.runtime_controls enable row level security;
alter table public.runtime_control_audits enable row level security;
alter table public.image_storage_limits enable row level security;
alter table public.operational_events enable row level security;

revoke all on table public.runtime_controls from public, anon, authenticated;
revoke all on table public.runtime_control_audits from public, anon, authenticated;
revoke all on table public.image_storage_limits from public, anon, authenticated;
revoke all on table public.operational_events from public, anon, authenticated;

grant select, insert, update, delete on table public.runtime_controls to service_role;
grant select, insert, update, delete on table public.runtime_control_audits to service_role;
grant select, insert, update, delete on table public.image_storage_limits to service_role;
grant select, insert, update, delete on table public.operational_events to service_role;
grant usage, select on sequence public.runtime_control_audits_id_seq to service_role;

revoke all on function public.ensure_image_storage_limit()
  from public, anon, authenticated;
revoke all on function public.get_user_image_storage_usage(text)
  from public, anon, authenticated;
revoke all on function public.update_runtime_control(text, boolean, text, text)
  from public, anon, authenticated;
revoke all on function public.record_operational_event(
  text, timestamptz, text, text, text, text, text, text, integer, text, text, jsonb
) from public, anon, authenticated;
revoke all on function public.cleanup_operational_events(timestamptz)
  from public, anon, authenticated;

grant execute on function public.ensure_image_storage_limit() to service_role;
grant execute on function public.get_user_image_storage_usage(text) to service_role;
grant execute on function public.update_runtime_control(text, boolean, text, text)
  to service_role;
grant execute on function public.record_operational_event(
  text, timestamptz, text, text, text, text, text, text, integer, text, text, jsonb
) to service_role;
grant execute on function public.cleanup_operational_events(timestamptz)
  to service_role;
